//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quaver.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quaver.Shared.Localization.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Songs.
        /// </summary>
        internal static string MainMenu_DownloadSongs {
            get {
                return ResourceManager.GetString("MainMenu_DownloadSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string MainMenu_Editor {
            get {
                return ResourceManager.GetString("MainMenu_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplayer.
        /// </summary>
        internal static string MainMenu_Multiplayer {
            get {
                return ResourceManager.GetString("MainMenu_Multiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string MainMenu_Options {
            get {
                return ResourceManager.GetString("MainMenu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Game.
        /// </summary>
        internal static string MainMenu_QuitGame {
            get {
                return ResourceManager.GetString("MainMenu_QuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Player.
        /// </summary>
        internal static string MainMenu_SinglePlayer {
            get {
                return ResourceManager.GetString("MainMenu_SinglePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Workshop.
        /// </summary>
        internal static string MainMenu_SteamWorkshop {
            get {
                return ResourceManager.GetString("MainMenu_SteamWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        internal static string MenuFooter_Github {
            get {
                return ResourceManager.GetString("MenuFooter_Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoplay.
        /// </summary>
        internal static string ModAutoplay_Name {
            get {
                return ResourceManager.GetString("ModAutoplay_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-op.
        /// </summary>
        internal static string ModCoop_Name {
            get {
                return ResourceManager.GetString("ModCoop_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Long Notes.
        /// </summary>
        internal static string ModFullLN_Name {
            get {
                return ResourceManager.GetString("ModFullLN_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize gameplay to your heart&apos;s desire.
        /// </summary>
        internal static string ModifierSelector_CustomizeGameplay {
            get {
                return ResourceManager.GetString("ModifierSelector_CustomizeGameplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked.
        /// </summary>
        internal static string ModifierSelector_Ranked {
            get {
                return ResourceManager.GetString("ModifierSelector_Ranked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These mods can be used for ranked scores.
        /// </summary>
        internal static string ModifierSelector_Ranked_Description {
            get {
                return ResourceManager.GetString("ModifierSelector_Ranked_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unranked.
        /// </summary>
        internal static string ModifierSelector_Unranked {
            get {
                return ResourceManager.GetString("ModifierSelector_Unranked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores will not be submitted while using these.
        /// </summary>
        internal static string ModifierSelector_Unranked_Description {
            get {
                return ResourceManager.GetString("ModifierSelector_Unranked_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse.
        /// </summary>
        internal static string ModInverse_Name {
            get {
                return ResourceManager.GetString("ModInverse_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judgement Windows.
        /// </summary>
        internal static string ModJudgementWindows_Name {
            get {
                return ResourceManager.GetString("ModJudgementWindows_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Adjustments.
        /// </summary>
        internal static string ModLongNoteAdjust_Name {
            get {
                return ResourceManager.GetString("ModLongNoteAdjust_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flips the map horizontally..
        /// </summary>
        internal static string ModMirror_Description {
            get {
                return ResourceManager.GetString("ModMirror_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror.
        /// </summary>
        internal static string ModMirror_Name {
            get {
                return ResourceManager.GetString("ModMirror_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Fail.
        /// </summary>
        internal static string ModNoFail_Name {
            get {
                return ResourceManager.GetString("ModNoFail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Long Notes.
        /// </summary>
        internal static string ModNoLongNotes_Name {
            get {
                return ResourceManager.GetString("ModNoLongNotes_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You miss, you die..
        /// </summary>
        internal static string ModNoMiss_Description {
            get {
                return ResourceManager.GetString("ModNoMiss_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Miss.
        /// </summary>
        internal static string ModNoMiss_Name {
            get {
                return ResourceManager.GetString("ModNoMiss_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Scroll Velocities.
        /// </summary>
        internal static string ModNoSliderVelocities_Name {
            get {
                return ResourceManager.GetString("ModNoSliderVelocities_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string ModPaused_Name {
            get {
                return ResourceManager.GetString("ModPaused_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize.
        /// </summary>
        internal static string ModRandomize_Name {
            get {
                return ResourceManager.GetString("ModRandomize_Name", resourceCulture);
            }
        }
    }
}
